chore(repos): 暂时只检查 arceos 仓库，排查 arceos_posix_api build.rs 的错误
ref: https://github.com/os-checker/os-checker/issues/30

error: failed to run custom build command for `arceos_posix_api v0.1.0 (/ci/arceos/api/arceos_posix_api)`

Caused by:
  process didn't exit successfully: `/ci/arceos/target/debug/build/arceos_posix_api-96ae6b51e318bb60/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=ctypes.h

  --- stderr
  thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.69.4/lib.rs:622:31:
  Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    Checking kernel_guard v0.1.1
    Checking linkme v0.3.27
    Checking percpu v0.1.3
    Checking bitmaps v3.2.1
    Checking kspin v0.1.0
   Compiling arceos_posix_api v0.1.0 (/ci/arceos/api/arceos_posix_api)
    Checking lazy_static v1.5.0
    Checking axlog v0.1.0 (/ci/arceos/modules/axlog)
    Checking axhal v0.1.0 (/ci/arceos/modules/axhal)
error: failed to run custom build command for `arceos_posix_api v0.1.0 (/ci/arceos/api/arceos_posix_api)`

Caused by:
  process didn't exit successfully: `/ci/arceos/target/debug/build/arceos_posix_api-96ae6b51e318bb60/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=ctypes.h

  --- stderr
  thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.69.4/lib.rs:622:31:
  Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: could not compile `axhal` (lib) due to 6 previous errors