fix(ci): bot 推送前 pull --rebase 来与远程仓库同步
Run # author zjp-CN, and commiter bot
os-checks/public/test.json 被添加到暂存
os-checks/public/test_raw_reports.json 被添加到暂存
正在提交 os-checks/public/test.json os-checks/public/test_raw_reports.json
[main ce55e91] [bot] update os-checks/public/test.json os-checks/public/test_raw_reports.json

 Author: zjp-CN <jiping_zhou@foxmail.com>
 2 files changed, 2 insertions(+), 2 deletions(-)
To https://github.com/os-checker/os-checker.github.io
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/os-checker/os-checker.github.io'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.