fix(nuxt): modules/ 貌似存放页面相关的模块，迁移 types 到 shared 目录
 ERROR  Error while requiring module [object Object]: Error: Cannot find module '/rust/my/os-checker/repos/ci/os-checks/modules/types_.ts/module'              10:20:53 AM
Require stack:
- /rust/my/os-checker/repos/ci/os-checks/index.js

 ERROR  Cannot find module '/rust/my/os-checker/repos/ci/os-checks/modules/types_.ts/module'                                                                   10:20:54 AM
Require stack:
- /rust/my/os-checker/repos/ci/os-checks/index.js

  Require stack:
  - index.js
  at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
  at Function.resolve (node:internal/modules/helpers:190:19)
  at Function._resolve [as resolve] (node_modules/jiti/dist/jiti.js:1:241814)
  at resolveModule (node_modules/@nuxt/kit/dist/index.mjs:2234:29)
  at requireModule (node_modules/@nuxt/kit/dist/index.mjs:2239:24)
  at loadNuxtModuleInstance (node_modules/@nuxt/kit/dist/index.mjs:2518:92)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:2470:47)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:4528:5)
  at async loadNuxt (node_modules/nuxt/dist/index.mjs:4695:5)
  at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:2660:19)